name: SvelteKit Deploy
run-name: Deploying newest commit to gh-pages
on: [push]
jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository code
        uses: actions/checkout@v4
      - run: cd ${{github.workspace}}
      - run: ls
      - run: npm install
      - run: npm deploy
      - run: echo "Github Action Job Status: ${{ job.status }}."
